version: 2.1

jobs:

  First-Job:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: First-Job First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: First-Job Second Step
          command: |
            ls -al
            echo '^^^The files in your repo^^^'
  
  # fetching code from the repo
  Fetch-Code:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Getting the Code
          command: |
            ls -al
            echo '^^^Your repo files^^^'
  
  # running a node container
  Second-Job:
    docker:
      - image: cimg/node:17.2
    steps:
      - run:
          name: Running the Node Container
          command: |
            node -v

workflows:
  Example-Workflow:
    jobs:
      - First-Job
      - Fetch-Code:
          requires:
            - First-Job
      - Second-Job:
          requires:
            - Fetch-Code
